name: massapp
description: A mobile application for learning management.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  video_player: ^2.6.1
  file_picker: ^5.2.5
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  flutter_secure_storage: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
